#애플리케이션 이름을 study로 설정
spring:
  application:
    name: study

  jpa:
    #트랜잭션이 종료되면 영속성 컨텍스트 종료
    #트랜잭션이 끝나면 JPA가 관리하던 엔티티 객체들이 더 이상 관리되지 않는다는 뜻
    #서비스계층에서 엔티티를 DTO로 변환 후 반환할 것
    open-in-view: false
    #애플리케이션이 완전히 시작된 후에 데이터베이스 초기화가 이루어지도록 설정
    defer-datasource-initialization: true
    hibernate:
      #애플리케이션 시작 시 테이블 자동 생성
      #create는 테이블 생성 후 유지됨(초기 개발단계), create-drop은 새로운 테이블 생성 후 종료 시 테이블 삭제(테스트 환경)
      ddl-auto: create
    properties:
      hibernate:
        #SQL을 보기 좋게 정렬
        format_sql: true
        #실행되는 SQL을 콘솔에 출력
        show_sql: true
        #MySQL 8.x 버전용 Hibernate SQL 방언 설정
        #데이터베이스에 맞게 SQL을 최적화하여 실행
        dialect: org.hibernate.dialect.MySQL8Dialect

  datasource:
    #로컬에서 실행되는 DB 사용
    #MySQL 기본 포트 사용
    #사용할 데이터베이스 이름
    url: jdbc:mysql://localhost:3306/studygroup
    username: root
    password: 1234
    #MySQL의 JDBC 드라이버 클래스 (MySQL 8.x 버전)
    driver-class-name: com.mysql.cj.jdbc.Driver